### ISSUE TITLE
Document minimum-known linux kernel version requirement

### ISSUE THREAD

**Issue by kevinworth** [facebook/bpfilter#14]
Potentially pairs with the new README.md note about libbpf 1.0 requirement.
This could also simply be a listing of the the earliest known-working/developer-tested version(s) of the kernel.

As of PR #12 I can't build on my kernel 5.15.x-based system. It seems the bpf_dynptr was [introduced to bpf-next in May 2022](https://lwn.net/Articles/895885/). Guessing that puts a minimum kernel for dynptr somewhere around 5.18 or 5.19, which is past that of stock Ubuntu, RHEL, and SLE/SUSE releases according to [wikipedia](https://en.wikipedia.org/wiki/Linux_kernel_version_history). libbpf 1.0.0 was August 22, 2022, so if libbpf and kernel need to move in-step, perhaps the required kernel is 6.0 or newer?

Totally understand if maintainers want to focus on current kernel releases rather than  optional configs and work-around for old kernels, but might help avoid further "issue" reports to document a known minimum.

**Comment by kevinworth** [comment]
A little more digging into the in-tree versions of libbpf:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/lib/bpf/libbpf_version.h?h=v5.18 has libbpf version 0.8
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/lib/bpf/libbpf_version.h?h=v5.19 has libbpf version 1.0

So if the kernel needs to be in-sync with at least libbpf 1.0 level of support, it seems the minimum linux kernel version for bpfilter could be 5.19.

**Comment by qdeslandes** [comment]
Thanks for raising this issue!

I haven't tested all the various kernel versions, but my expectations are the following:
- Kernel 5.19+
- libbpf 1.0+

I use Fedora 38 with Linux 6.4.10 and libbpf 1.1 without any issue. For Ubuntu:
- 22.04: build failure due to missing `struct bpf_dynptr`. While [Linux 5.19 is available in the updates repositories](https://packages.ubuntu.com/jammy-updates/linux-generic), the [userspace headers package is limited to 5.15](https://packages.ubuntu.com/jammy-updates/linux-libc-dev).
- 22.10: both [userspace headers](https://packages.ubuntu.com/kinetic/linux-libc-dev) and [Linux version](https://packages.ubuntu.com/kinetic/linux-generic) are at least 5.19, but [libbpf is only 0.8](https://packages.ubuntu.com/kinetic/libbpf-dev). `bpfilter` builds but fails at runtime as libbpf can't find `bpf_dynptr_from_skb` BTF ID.
- 23.10: userspace headers and Linux are recent enough (6.2), as is libbpf (1.1). `bpfilter` builds but I have the same runtime failure as with Ubuntu 22.10.

I won't do much about Ubuntu 22.04 due to the old userspace headers, but 23.10 should work fine. For 22.10, even though it doesn't meet the libbpf 1.0 requirements, it might work, but I probably won't dedicate development time to support it.

I will update the readme with more details about my configuration. Hopefully, I'll be able to investigate the Ubuntu runtime issue soon and list supported Ubuntu versions in the readme.

**Comment by qdeslandes** [comment]
Also, with support for `BPF_PROG_TYPE_NETFILTER` in progress, the minimal kernel version will soon be bumped.

**Comment by kevinworth** [comment]
This is great info, thank you! Will close this issue since there's at least some base information for folks who are getting started.
