### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [facebook/bpfilter#34]
:eyes: I would like to point out that identifiers like “[`_bf_opts_parser`](https://github.com/facebook/bpfilter/blob/1b2a71a6099de8ad717da6f5ca88147b9da7ede7/src/opts.c#L57 "Update candidate")” and “[`_stop_received`](https://github.com/facebook/bpfilter/blob/1b2a71a6099de8ad717da6f5ca88147b9da7ede7/src/main.c#L32 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C language standard.
:thought_balloon: Would you like to adjust your selection for unique names?

**Comment by qdeslandes** [comment]
Hi @elfring 

Thanks for your concern. I try to stick to the `_bf_` prefix for the symbols with static linkage, so I don't expect this to be a real concern. This rule is useful to quickly distinguish static symbols in a file, while having a common prefix with low chances to introduce name clashes.

However, you can see that this rule has been loosely followed until recently, and you're welcome to submit a PR if you want to!

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/reserved-identifier.html "Checking the application of reserved identifiers")?

**Comment by qdeslandes** [comment]
`clang-tidy` [is used](https://github.com/facebook/bpfilter/blob/1b2a71a6099de8ad717da6f5ca88147b9da7ede7/.clang-tidy), but it doesn't define the rules for the project to follow. I define the rules, and for this specific case (reserved identifiers), I've explained the rational in my message above.

**Comment by elfring** [comment]
:thought_balloon: How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by qdeslandes** [comment]
I've answered in good faith so far, even though [your](https://lore.kernel.org/all/c17648db-469c-4d3c-8c2e-774b88e79f07@kernel.dk/) [track](https://lore.kernel.org/all/ZZ6kqV79ckeZ7JUj@shell.armlinux.org.uk/) [record](https://lore.kernel.org/all/20240123174625.GO254773@kernel.org/) [of](https://lore.kernel.org/all/b21cb419-678e-b67d-23f2-c922b4a4f7a@inria.fr/) [public](https://lore.kernel.org/all/a487afb1-315e-4b90-9bac-591d422136f8@web.de/) [contribution](https://lore.kernel.org/all/2023070919-monetary-sleet-2f5c@gregkh/) doesn't play in your favor. I've explained the reasoning for prefixing symbols with `_bf_`. I won't allow this discussion to waste my time further, because I think you're acting in bad faith.

Now, if you come up with a real world use case were bpfilter is causing symbols clash, you're free to create a PR.

**Comment by elfring** [comment]
:thought_balloon: I guess that you can get a more positive impression for [my contribution spectrum](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/?qt=author&q=Elfring "Selection of Linux adjustments").

:crystal_ball: I hope that development interests can grow also for compliance with the rules of the programming language “C”.
